[server]
port=8502 # change port number. By default streamlit uses 8502 port
address = "0.0.0.0"
headless=true # This will eliminate automatically open browser
enableCORS=false 
enableXsrfProtection=false 
enableWebsocketCompression=false
enableStaticServing = true

[browser] # This ip and port will show in command prompt
#serverAddress = " "
serverPort = 8502
gatherUsageStats = false

[theme]
primaryColor="#2F2E78"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"


